### PR TITLE
manage /etc/dnsmasq.conf to ensure /etc/dnsmasq.d configs are used

### PR DESCRIPTION
**Pull request by cwjohnston**
Resolves #9, fixes centos-6.6 platform tests

### CODE REVIEW

**Comment by jtimberman** [comment]
Do any of the supported distributions ship an `/etc/dnsmasq.conf` that this could smash in a bad way?

**Comment by cwjohnston** [comment]
My testing revealed that the supported distributions ship a config whose only uncommented line is the `conf-dir=/etc/dnsmasq.d` directive, except centos-6.6 which ships a config that is entirely commented out.

**Comment by jtimberman** [comment]
:+1:  then!

**Comment by jtimberman** [comment]
Not that you need my approval :cake:

**Comment by scalp42** [comment]
@cwjohnston @jtimberman any chance to see this merged?

**Comment by jtimberman** [comment]
I can't merge in this repo, up to @cwjohnston.

**Pull request merged**
